In [ ]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 33.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 29.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 20.1 MB/s eta 0:00:00


In [ ]:
import csv
import openai
from matplotlib import pyplot
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import numpy as np
import time

In [ ]:
#metricas


openai.api_key = "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"
file = open('Reddit_Data.csv',encoding="utf8")

linhas = csv.reader(file)

predicted = []
expected = []

header = 0

for linha in linhas:
  try:
      completion = openai.Completion.create(
          engine="text-davinci-003",
          prompt=f"please, classify the following sentence as: 1 for Positive sentimental in sentence or -1 for Negative sentimental in sentence: '{linha[0]}'. Just return numbers that represents the class, please.",
          max_tokens=1024,
          n=1,
          stop=None,
          temperature=0.5,
      )

      response = completion.choices[0].text
      chars = '\n.'
      response = response.translate(str.maketrans('', '', chars))

      row = response + ',' + linha[1]

      print(row)

      if header == 0: 
        header+=1
      else:
        response = int(response)
        linha[1] = int(linha[1])

        predicted.append(response)
        expected.append(linha[1])

  except:
      break

certos = list()
erros = list()

for i in range(len(expected)):
  if expected[i] == predicted[i]:

    certos.append(0)
  else:
    erros.append(0)

#acurácia = (número de exemplos classificados corretamente) / (total de exemplos)
print("acurácia:", len(certos) / len(expected) )


conf_matrix = confusion_matrix(expected, predicted, labels=[-1, 0, 1])

print(f'\n A matriz de confusão \n {conf_matrix} \n')

precisao_a = precision_score(expected, predicted, labels=[-1], average='micro')
precisao_b = precision_score(expected, predicted, labels=[0], average='micro')
precisao_c = precision_score(expected, predicted, labels=[1], average='micro')
print(f'A precisão da classe -1 é {precisao_a}')
print(f'A precisão da classe  0 é {precisao_b}')
print(f'A precisão da classe 1 é {precisao_c}')

recall_a = recall_score(expected, predicted, labels=[-1], average='micro')
recall_b = recall_score(expected, predicted, labels=[0], average='micro')
recall_c = recall_score(expected, predicted, labels=[1], average='micro')
print(f'O recall da classe -1 é {recall_a}')
print(f'O recall da classe 0 é {recall_b}')
print(f'O recall da classe 1 é {recall_c}')

f1_score_a = f1_score(expected, predicted, labels=[-1], average='micro')
f1_score_b = f1_score(expected, predicted, labels=[0], average='micro')
f1_score_c = f1_score(expected, predicted, labels=[1], average='micro')
print(f'O F1-Score da classe -1 é {f1_score_a}')
print(f'O F1-Score da classe 0 é {f1_score_b}')
print(f'O F1-Score da classe 1 é {f1_score_c}')


0,category
1,1
1,1
-1,-1
0,0
1,1
1,-1
-1,1
0,0
1,-1
1,1
1,1
0,1
1,1
1,1
1,1
-1,-1
0,1
0,-1
-1,0
1,1
0,-1
1,-1
1,1
1,-1
0,0
-1,-1
-1,-1
1,-1
-1,-1
0,1
-1,-1
1,1
-1,-1
1,1
0,1
0,1
1,1
1,1
1,1
1,1
1,1
1,1
0,1
0,1
1,1
0,0
-1,-1
0,-1
-1,-1
0,1
0,-1
0,1
1,1
1,1
0,1
0,1
0,1
1,-1
-1,1
1,-1
-1,0
1,1
0,1
-1,1
0,0
-1,1
1,0
0,0
0,1
0,0
-1,-1
0,0
0,0
0,1
0,0
0,0
0,1
0,1
1,1
-1,-1
0,-1
1,1
-1,-1
-1,-1
0,1
0,1
0,0
0,-1
0,-1
0,1
0,0
0,-1
0,-1
0,1
-1,1
-1,-1
0,-1
1,1
-1,-1
0,0
0,1
0,0
-1,1
0,0
-1,1
0,0
-1,1
-1,0
0,0
0,1
-1,1
-1,0
1,1
1,0
-1,-1
0,0
-1,0
1,0
0,0
-1,0
-1,0
0,1
1,1
-1,1
1,1
0,1
1,1
1,1
0,1
-1,0
0,1
-1,1
1,1
0,-1
-1,1
-1,0
0,1
-1,-1
0,0
0,0
1,1
0,1
1,1
1,1
0,1
1,1
1,1
1,1
0,1
0,-1
0,0
0,-1
0,0
-1,-1
-1,-1
-1,-1
1,1
-1,0
1,1
0,1
-1,-1
0,0
-1,-1
1,1
1,1
-1,0
1,1
1,1
-1,0
0,1
1,1
0,1
1,0
0,1
1,1
0,0
acurácia: 0.5284090909090909

 A matriz de confusão 
 [[22 13  7]
 [12 26  4]
 [12 35 45]] 

A precisão da classe -1 é 0.4782608695652174
A precisão da classe  0 é 0.35135135135135137
A precisão da